Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -1,1 +1,29 @@
 
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+          gradle-version: "8.13"
+
+      - name: Check Project Files
+        run: |
+          echo "Isi repository:"
+          ls -la
+
+          if [ ! -f "app/build.gradle.kts" ]; then
+            echo "ERROR: app/build.gradle.kts tidak ditemukan"
+            exit 1
+          fi
+
+          if [ ! -f "settings.gradle.kts" ]; then
+            echo "ERROR: settings.gradle.kts tidak ditemukan"
+            exit 1
+          fi
+
+      - name: Check Gradle
+        run: gradle --version
+
+      - name: Build Debug APK
+        run: gradle assembleDebug --stacktrace
+
+      - name: Build Release APK
+        run: gradle assembleRelease --stacktrace
